services:
  # 1. Primary Database
  postgres:
    image: postgres:15-alpine
    container_name: ticketflow-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Speed Layer
  redis:
    image: redis:7-alpine
    container_name: ticketflow-redis
    ports:
      - "6379:6379"

  # 3. Message Broker
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 4. Metrics Collector
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: ticketflow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # We will create this file next
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  # 5. Visualization Dashboard
  grafana:
    image: grafana/grafana:9.5.2
    container_name: ticketflow-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
