server:
  port: 8080

spring:
  application:
    name: ticketflow

  # Database Config
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketflow_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development, 'validate' or 'none' for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Config
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka Config
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticket-group
      auto-offset-reset: earliest
