server:
  port: 8080
  error:
    include-message: always
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: ticketflow

  # Database Config
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/ticketflow_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development, 'validate' or 'none' for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Config
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # Kafka Config
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ticket-group
      #max-poll-records: 1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"

# --- MONITORING CONFIG ---
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ticketflow
    distribution:
      percentiles-histogram:
        # FIX: Escape the key so it treats "http.server.requests" as one string
        "[http.server.requests]": true
logging:
  level:
    "[org.apache.kafka.clients.NetworkClient]": ERROR
    "[org.apache.kafka.clients.consumer.internals]": ERROR
    "[org.springframework.kafka]": WARN
